### ISSUE TITLE
DK AQ40 Loot is bugged

### ISSUE THREAD

**Issue by Chromie-the-gnome** [BelsethUwU/AtlasLoot_Duskhaven#1]
While opening the AQ40 Sets and selecting the dk tab the following section shows using the latest downloadable version.
![image](https://user-images.githubusercontent.com/31871078/236280936-fb6dfec3-9a9d-4742-85f8-b31089adda3c.png)

**Comment by IllustreDot** [comment]
Hi,
I don't know what's currently causing the issues but it does get fixed if you just click on another menu and then comeback to the menu you wanted to click on. This issue can also happen on other menu that has submenu.
If ever the issues keep happening even through what I just said. Please let me know.
